name: Trigger auto deployment for process1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/process1-AutoDeployTrigger-0a22ce83-e97b-4107-8dce-07d40e1bab6d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: yaliacr.azurecr.io
          username: ${{ secrets.PROCESS1_REGISTRY_USERNAME }}
          password: ${{ secrets.PROCESS1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yaliacr.azurecr.io/process1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROCESS1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n process1 -g nonvnet-nonlong-eastus-rg --server yaliacr.azurecr.io --username  ${{ secrets.PROCESS1_REGISTRY_USERNAME }} --password ${{ secrets.PROCESS1_REGISTRY_PASSWORD }}
            az containerapp update -n process1 -g nonvnet-nonlong-eastus-rg --image yaliacr.azurecr.io/process1:${{ github.sha }}
