name: Trigger auto deployment for yali-policy-capp-st

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yali-policy-capp-st-AutoDeployTrigger-7d84ca0d-f72c-4cf6-b35b-30bb7c89f023.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: yaliacr.azurecr.io
          username: ${{ secrets.YALIPOLICYCAPPST_REGISTRY_USERNAME }}
          password: ${{ secrets.YALIPOLICYCAPPST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yaliacr.azurecr.io/yali-policy-capp-st:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YALIPOLICYCAPPST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n yali-policy-capp-st -g yali-policy --server yaliacr.azurecr.io --username  ${{ secrets.YALIPOLICYCAPPST_REGISTRY_USERNAME }} --password ${{ secrets.YALIPOLICYCAPPST_REGISTRY_PASSWORD }}
            az containerapp update -n yali-policy-capp-st -g yali-policy --image yaliacr.azurecr.io/yali-policy-capp-st:${{ github.sha }}
